[package]
name = "action_app"
version = "0.1.0"
authors = ["adrian"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
serde = "1.0.104"
serde_json = "1.0.44"
serde_derive = "1.0.104"
rocket_contrib = "0.4.2"
dotenv = "0.11.0"
mysql = "*"
