version: '3.1'

services:

  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8777:8000
    depends_on:
      - db 
    links:
      - "db:database"   

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3399:3306  
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: gamedb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8050:8080    

    
